production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") %>
:queues:
  - default
  - es_index
:limits:
  default: 3
  es_index: 2
:schedule:
  measures_sync:
    cron: <%= ENV.fetch("SYNCHRONIZATION_CRON_INTERVAL", '0 */15 * * * *') %> # runs every 15 minutes
    class: MeasuresSyncJob
  weight_measures_sync:
    cron: <%= ENV.fetch("SYNCHRONIZATION_CRON_INTERVAL", '0 */15 * * * *') %> # runs every 15 minutes
    class: WeightMeasuresSyncJob  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
