production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") %>
:queues:
  - default
  - es_index
:limits:
  es_index: 1
:schedule:
  measures_sync:
    cron: '0 */15 * * * *' # runs every 15 minutes
    class: MeasuresSyncJob
  measures_sync:
    cron: '0 0 * * * *' # runs every 1 hour
    class: WeightMeasuresSyncJob  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
